### ISSUE TITLE
How do I change the font?

### ISSUE THREAD

**Issue by Khhd1** [Litzuck/lol-spectator-overlay-client#12]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/82941693/117823301-e8c99000-b29f-11eb-85c1-1693e19352b9.png)
I want to change the font for the countdown

**Comment by Litzuck** [comment]
Thanks for your feature request, but this won't be high on my priority list of new features, so don't expect anything soon.
If you realy need another font you can always customize it by editing the code yourself or you can try to implement it yourself and open a pull request so others can use it too.

**Comment by ArimaTsuchimikado** [comment]
For change all font you can write this on .css

```css
code {
    font-family: source-code-pro,Menlo,Monaco,Consolas,"Courier New",monospace
}

@font-face {
    font-family: BeaufortforLOL-Bold;
    src: url(../../static/media/beaufortforlol-bold.4effc8d5.otf) format("opentype")
}
```
(yes it's ugly, sorry ;) )

[beaufortforlol-bold.4effc8d5.otf.zip](https://github.com/Litzuck/lol-spectator-overlay-client/files/6468543/beaufortforlol-bold.4effc8d5.otf.zip)

**Comment by Sky-CSC** [comment]
You can write this on the .css
```css
@font-face {
    font-family: BeaufortforLOL-Bold;
    src: url(../../static/media/beaufortforlol-bold.4effc8d5.otf) format("OpenType");
}

div {
    font-family: BeaufortforLOL-Bold;
}
```
[beaufortforlol-bold.4effc8d5.otf.zip](https://github.com/Litzuck/lol-spectator-overlay-client/files/6468984/beaufortforlol-bold.4effc8d5.otf.zip)
